name: Deploy to Stage

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Deploy to Stage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set up Composer caching
        uses: actions/cache@v3
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies in prod version
        run: |
          composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer install --no-dev
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy the code to the GTS site
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -cvzr --delete --exclude-from=.distignore --chmod=D775,F664
          path: ${{ env.GITHUB_WORKSPACE }}
          remote_path: /var/www/gts/wp-content/plugins/gts-wp-translator/
          remote_host: 34.228.113.92
          remote_user: igor
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy the code to the blog site
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -cvzr --delete --exclude-from=.distignore --chmod=D775,F664
          path: ${{ env.GITHUB_WORKSPACE }}
          remote_path: /var/www/blog/wp-content/plugins/gts-wp-translator/
          remote_host: 34.228.113.92
          remote_user: igor
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy the code to the eallanh site
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -cvzr --delete --exclude-from=.distignore --chmod=D775,F664
          path: ${{ env.GITHUB_WORKSPACE }}
          remote_path: /var/www/eallanh/wp-content/plugins/gts-wp-translator/
          remote_host: 34.228.113.92
          remote_user: igor
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy the code to the test.kagg.eu site
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -cvzr --delete --exclude-from=.distignore --chmod=D775,F664
          path: ${{ env.GITHUB_WORKSPACE }}
          remote_path: /var/www/test/wp-content/plugins/gts-wp-translator/
          remote_host: 139.59.153.194
          remote_user: igor
          remote_key: ${{ secrets.DEPLOY_KAGG_KEY }}
